### PR TITLE
add a notebook that describes how to compute the ela

### PR DESCRIPTION
**Pull request by anoukvlug**
This PR contains a first version for a notebook on the compute_ela and compile_ela functions.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks @anoukvlug ! What do you think about adding a section to https://oggm.org/tutorials/master/notebooks/plot_mass_balance.html and call the notebook "Plotting the surface mass-balance and ELA"?

**Comment by anoukvlug** [comment]
I think that is a nice idea. I can add such a section to that notebook later this week.

**Comment by fmaussion** [comment]
Thanks @anoukvlug ! Sorry I let this linger for so long

**Comment by anoukvlug** [comment]
@fmaussion, no worries and thanks for merging it :)

**Pull request merged**
