### PR TITLE
Additions to the where_are_the_flowlines notebook

### PR DESCRIPTION
**Pull request by anoukvlug**
This PR addresses issue #35 and adds to the where_are_the_flowlines notebook. It adds a part about the new flowline diagnostics.

I would be happy if someone would provide feedback :) (e.g. if it is clear/ if your missing something/ if it's to long)

### CODE REVIEW

**Comment by fmaussion** [comment]
I like it, thanks!! But I think you should use the opportunity to write text in notebook cells as well! (instead of using code comments only as you do right now)

**Comment by anoukvlug** [comment]
Thanks for the suggestion :) I will change that.

**Comment by fmaussion** [comment]
That's great thanks! I made some suggestions. In the process I realized one or two things that need attention in OGGM, let;s discuss tomorrow ;-)

**Comment by fmaussion** [comment]
Thanks @anoukvlug !

**Pull request merged**
