### PR TITLE
Tutorial about the use of `cook_rgidf()` function

### PR DESCRIPTION
**Pull request by Keeptg**
This is a simple tutorial about the use of `cook_rgidf()` function. Despite there is still huge room to improve the function, it can still give some reference to users who want to use their own glacier inventory data but don't know how to do.

### CODE REVIEW

**Comment by Keeptg** [comment]
The situation seems not good!
Is there any suggestions?

**Comment by fmaussion** [comment]
Yes this is again some weird notebook specification which doesn't work with how we build the book. Not much we can do about it can we @TimoRoth ? 

Once the PR is done in OGGM I'll try to edit the notebook myself to see if it solves this.

**Comment by fmaussion** [comment]
@Keeptg thanks! Please update with the new function signature and I will have a look

**Comment by fmaussion** [comment]
Thanks!

**Pull request merged**
